### ISSUE TITLE
Facing Issues while send VOIP

### ISSUE THREAD

**Issue by sasi22002** [nnsnodnb/kalyke#194]
Hello,
      Im working as python developer.Im using this package for send voip notification to ios.Now Im facing issue in send voip notification.
      I have this error "ssl.SSLError: [SSL] PEM lib (_ssl.c:4065)".but i was configured my pem file but we got this issue

**Comment by nnsnodnb** [comment]
Thank you for using kalyke!

Could you please check the following two points?

1. Is there a password set in pem file?  
If it is set, try the implementation without a password.

2. Is private key included in pem file?

**Comment by sasi22002** [comment]
Thanks for reply, I have answered for your questions

1.We didnt set any password for our pem file
2.No 

we just created a VOIP certificate from apple,then we convert the cer file to pem file and used that for sending voip notification

**Comment by nnsnodnb** [comment]
I'm sorry.

For now, it is possible to connect only with a pem format certificate that includes a private key.
For now, it is possible to connect only with a pem format certificate that includes a private key.
Then I think it will be successful by converting the exported p12 file to pem format and reading it.

```bash
openssl pkcs12 -in certs.p12 -out certs.pem -nodes
```

In future updates, I will consider an implementation that will work even if the cer file and the private key are separated.

Thank you for raising this problem!

**Comment by nnsnodnb** [comment]
I have released v1.0.2 which supports certificates separated into `cer` and private key.

https://github.com/nnsnodnb/kalyke/releases/tag/1.0.2

**Comment by sasi22002** [comment]
Hi...Thanks ...We fixed that issue by using private key included pem file.

**Comment by nnsnodnb** [comment]
I'm glad I was able to solve it.

If there doesn't seem to be a problem, I'd appreciate it if you could close the issue.

Thank you.
