### ISSUE TITLE
support for apn-push-type

### ISSUE THREAD

**Issue by nikitph** [nnsnodnb/kalyke#8]
this is necessary for voip push notifications to be sent to the production env. should just be a 2-3 line change

**Comment by nnsnodnb** [comment]
@nikitph Thank you.
I think it will take some time, but I would like to implement it.
I'm waiting for a pull request if you like 🚀 

## `apns-push-type`

| set value | description |
| :-------: | :----------- |
| `background` | for background push notification |
| `alert` | normal or default push notification |
| `voip` | for VoIP push notification |

**Comment by nikitph** [comment]
no problem, a pull request will be incoming. Although can you confirm if the following fields are populated in the header. they are all now required 


Header field | Description
-- | --
:method | (Required) The value POST.
:path | (Required) The path to the device token. The value of this header is /3/device/<device_token>, where <device_token> is the hexadecimal bytes that identify the user’s device. Your app receives the bytes for this device token when registering for remote notifications; see Registering Your App with APNs.
authorization | (Required for token-based authentication) The value of this header is bearer <provider_token>, where <provider_token> is the encrypted token that authorizes you to send notifications for the specified topic. APNs ignores this header if you use certificate-based authentication. For more information, see Establishing a Token-Based Connection to APNs.
apns-push-type | (Required for watchOS 6 and later; recommended for macOS, iOS, tvOS, and iPadOS) The value of this header must accurately reflect the contents of your notification’s payload. If there is a mismatch, or if the header is missing on required systems, APNs may return an error, delay the delivery of the notification, or drop it altogether.
